### ISSUE TITLE
running node with --use-strict causes failure

### ISSUE THREAD

**Issue by drewandersonnz** [shamil/node-zabbix-sender#1]
/node_modules/node-zabbix-sender/index.js:97
        if (response.slice(0, 5).toString() !== 'ZBXD\1') {
                                                      
SyntaxError: Octal literals are not allowed in strict mode.
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)

**Comment by shamil** [comment]
Added support for strict-mode. Please upgrade to latest version (`1.0.8`).

**Comment by drewandersonnz** [comment]
Works great, thanks!
